export const questions = [
    {
        id:1,
        question:"section1",
        answer:"answer1"
    },
    {
        id:2,
        question:"section2",
        answer:"answer2"
    },
    {
        id:3,
        question:"section3",
        answer:"answer3"
    },
    {
        id:4,
        question:"section4",
        answer:"answer4"
    },
    {
        id:5,
        question:"section5",
        answer:"answer5"
    },
]